"""
Stock universe for the screener.

This is a hand-picked list of liquid, large/mid-cap NSE stocks (roughly the
Nifty 200 constituents as of late 2025). Using a fixed list instead of
scraping any website keeps this 100% within data-provider terms of use --
we only pull public OHLCV price history from Yahoo Finance via yfinance,
never scrape a paid/ToS-restricted site.

Edit this list any time: add tickers you want covered, remove ones you don't
care about. Format is "<NSE_SYMBOL>.NS" (yfinance's suffix for NSE).
"""

NIFTY_UNIVERSE = [
    "RELIANCE.NS", "TCS.NS", "HDFCBANK.NS", "ICICIBANK.NS", "INFY.NS",
    "HINDUNILVR.NS", "ITC.NS", "SBIN.NS", "BHARTIARTL.NS", "BAJFINANCE.NS",
    "KOTAKBANK.NS", "LT.NS", "AXISBANK.NS", "ASIANPAINT.NS", "MARUTI.NS",
    "SUNPHARMA.NS", "TITAN.NS", "ULTRACEMCO.NS", "WIPRO.NS", "NESTLEIND.NS",
    "ADANIENT.NS", "ADANIPORTS.NS", "TATASTEEL.NS", "TMPV.NS", "M&M.NS",
    "POWERGRID.NS", "NTPC.NS", "HCLTECH.NS", "BAJAJFINSV.NS", "ONGC.NS",
    "TECHM.NS", "INDUSINDBK.NS", "JSWSTEEL.NS", "GRASIM.NS", "DIVISLAB.NS",
    "CIPLA.NS", "DRREDDY.NS", "BRITANNIA.NS", "EICHERMOT.NS", "HEROMOTOCO.NS",
    "COALINDIA.NS", "BPCL.NS", "HINDALCO.NS", "APOLLOHOSP.NS", "SBILIFE.NS",
    "HDFCLIFE.NS", "BAJAJ-AUTO.NS", "SHREECEM.NS", "UPL.NS", "TATACONSUM.NS",
    "PIDILITIND.NS", "DABUR.NS", "GODREJCP.NS", "MARICO.NS", "COLPAL.NS",
    "SIEMENS.NS", "ABB.NS", "HAVELLS.NS", "DLF.NS", "BANKBARODA.NS",
    "PNB.NS", "CANBK.NS", "IDFCFIRSTB.NS", "FEDERALBNK.NS", "AUBANK.NS",
    "BANDHANBNK.NS", "PFC.NS", "RECLTD.NS", "IRFC.NS", "GAIL.NS",
    "IOC.NS", "VEDL.NS", "SAIL.NS", "NMDC.NS", "JINDALSTEL.NS",
    "AMBUJACEM.NS", "ACC.NS", "DIXON.NS", "TRENT.NS", "ETERNAL.NS",
    "NYKAA.NS", "PAYTM.NS", "IRCTC.NS", "INDIGO.NS", "PGHH.NS",
    "MOTHERSON.NS", "BOSCHLTD.NS", "MRF.NS", "BALKRISIND.NS", "TVSMOTOR.NS",
    "ASHOKLEY.NS", "CUMMINSIND.NS", "LUPIN.NS", "AUROPHARMA.NS", "ALKEM.NS",
    "TORNTPHARM.NS", "BIOCON.NS", "MPHASIS.NS", "PERSISTENT.NS", "LTIM.NS",
    "COFORGE.NS", "OFSS.NS", "MUTHOOTFIN.NS", "CHOLAFIN.NS", "SRF.NS",
    "PIIND.NS", "DEEPAKNTR.NS", "NAUKRI.NS", "POLYCAB.NS", "VOLTAS.NS",
]

# Sector of each stock -- the bot won't hold two positions from the same
# sector at once (bank stocks, for instance, tend to fall together).
SECTORS = {
    "TCS": "IT",
    "INFY": "IT",
    "WIPRO": "IT",
    "HCLTECH": "IT",
    "TECHM": "IT",
    "LTIM": "IT",
    "MPHASIS": "IT",
    "PERSISTENT": "IT",
    "COFORGE": "IT",
    "OFSS": "IT",
    "HDFCBANK": "Bank",
    "ICICIBANK": "Bank",
    "SBIN": "Bank",
    "KOTAKBANK": "Bank",
    "AXISBANK": "Bank",
    "INDUSINDBK": "Bank",
    "BANKBARODA": "Bank",
    "PNB": "Bank",
    "CANBK": "Bank",
    "IDFCFIRSTB": "Bank",
    "FEDERALBNK": "Bank",
    "AUBANK": "Bank",
    "BANDHANBNK": "Bank",
    "BAJFINANCE": "NBFC",
    "BAJAJFINSV": "NBFC",
    "PFC": "NBFC",
    "RECLTD": "NBFC",
    "IRFC": "NBFC",
    "MUTHOOTFIN": "NBFC",
    "CHOLAFIN": "NBFC",
    "SBILIFE": "Insurance",
    "HDFCLIFE": "Insurance",
    "MARUTI": "Auto",
    "TMPV": "Auto",
    "M&M": "Auto",
    "EICHERMOT": "Auto",
    "HEROMOTOCO": "Auto",
    "BAJAJ-AUTO": "Auto",
    "TVSMOTOR": "Auto",
    "ASHOKLEY": "Auto",
    "MOTHERSON": "Auto",
    "BOSCHLTD": "Auto",
    "MRF": "Auto",
    "BALKRISIND": "Auto",
    "SUNPHARMA": "Pharma",
    "DIVISLAB": "Pharma",
    "CIPLA": "Pharma",
    "DRREDDY": "Pharma",
    "LUPIN": "Pharma",
    "AUROPHARMA": "Pharma",
    "ALKEM": "Pharma",
    "TORNTPHARM": "Pharma",
    "BIOCON": "Pharma",
    "APOLLOHOSP": "Pharma",
    "HINDUNILVR": "FMCG",
    "ITC": "FMCG",
    "NESTLEIND": "FMCG",
    "BRITANNIA": "FMCG",
    "TATACONSUM": "FMCG",
    "DABUR": "FMCG",
    "GODREJCP": "FMCG",
    "MARICO": "FMCG",
    "COLPAL": "FMCG",
    "PGHH": "FMCG",
    "TATASTEEL": "Metal",
    "JSWSTEEL": "Metal",
    "HINDALCO": "Metal",
    "VEDL": "Metal",
    "SAIL": "Metal",
    "NMDC": "Metal",
    "JINDALSTEL": "Metal",
    "COALINDIA": "Metal",
    "RELIANCE": "Energy",
    "ONGC": "Energy",
    "BPCL": "Energy",
    "GAIL": "Energy",
    "IOC": "Energy",
    "POWERGRID": "Power",
    "NTPC": "Power",
    "ULTRACEMCO": "Cement",
    "SHREECEM": "Cement",
    "AMBUJACEM": "Cement",
    "ACC": "Cement",
    "GRASIM": "Cement",
    "LT": "CapGoods",
    "SIEMENS": "CapGoods",
    "ABB": "CapGoods",
    "HAVELLS": "CapGoods",
    "CUMMINSIND": "CapGoods",
    "POLYCAB": "CapGoods",
    "VOLTAS": "CapGoods",
    "DIXON": "CapGoods",
    "ASIANPAINT": "Chemicals",
    "PIDILITIND": "Chemicals",
    "UPL": "Chemicals",
    "SRF": "Chemicals",
    "PIIND": "Chemicals",
    "DEEPAKNTR": "Chemicals",
    "DLF": "Realty",
    "BHARTIARTL": "Telecom",
    "TITAN": "Retail",
    "TRENT": "Retail",
    "ETERNAL": "Retail",
    "NYKAA": "Retail",
    "DMART": "Retail",
    "PAYTM": "Internet",
    "NAUKRI": "Internet",
    "IRCTC": "Internet",
    "ADANIENT": "Infra",
    "ADANIPORTS": "Infra",
    "INDIGO": "Infra",
}


def sector_of(sym: str) -> str:
    return SECTORS.get(sym.replace(".NS", ""), "Other")
